[options]
ascii = true

[outline]
ascii = false
instruction-file = outline.txt
; model = openai/gpt-5.6-luna
mode = analysis
reasoning_effort = low

[translate]
instruction-file = translate.txt
; model = openai/gpt-oss-120b:nitro
; mode = paragraph
mode = chunk
reasoning_effort = none
strict_fidelity = true

[review]
instruction-file = review.txt
; model = openai/gpt-5.6-luna
mode = chunk
reasoning_effort = medium
strict_fidelity = true
